# Generated by Django 5.1.6 on 2025-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер'),
        ),
    ]
