# Generated by Django 5.1.6 on 2025-06-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asort', '0002_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Введите размер свободно, например: 46, 47, XL, M и т.д.', max_length=10, null=True, verbose_name='Размер'),
        ),
    ]
